#pragma once

#include "NativeGameplayTags.h"

namespace CrunchGameplayTags
{
	CRUNCH_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
	
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Passive_Launch_Activate);

	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Dead);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Stun);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Aim);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Focus);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Crosshair);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Health_Full);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Health_Empty);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Mana_Full);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Mana_Empty);
	
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Hero);

	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attr_Experience);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attr_Gold);
	
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack_Pressed);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack_Released);
	
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Damage);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_Combo01);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_Combo02);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_Combo03);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_Combo04);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_End);

	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_UpperCut_Launch);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_UpperCut_Cooldown);

	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_GroundBlast_Cooldown);
	
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shoot);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shoot_LeftHand);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shoot_RightHand);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Updated);

	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Lazer_Shoot);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Lazer_Cooldown);

	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BlackHole_Cooldown);
	
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_CameraShake);
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_GroundBlast);


	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Test_Cooldown);
}
